Lab8 : Lab8.o card.o deck.o rank.o
	g++ *.o -o Lab8
Lab8.o : Lab8.cpp
	g++ -c Lab8.cpp
card.o : card.cpp
	g++ -c card.cpp
deck.o : deck.cpp
	g++ -c deck.cpp
rank.o : rank.cpp
	g++ -c rank.cpp
clean :
	rm -i *.o Lab8
